import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import CustomModal from "@/components/modal";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.custom_modal}>
          <CustomModal />
        </div>
        <div className={`${styles.main} ${inter.className}`}>
          <div className={styles.grid}>
            <Link href="/login" className={styles.card}>
              <h2>
                Login <span>-&gt;</span>
              </h2>
              <p>
                Use your email and password to login if you already have an
                account.
              </p>
            </Link>

            <Link href="/sign-up" className={styles.card}>
              <h2>
                Sign Up <span>-&gt;</span>
              </h2>
              <p>
                Don&apos;t have an account? Head over to this page and create
                one right now!
              </p>
            </Link>

            <Link href="/profile" className={styles.card}>
              <h2>
                Profile <span>-&gt;</span>
              </h2>
              <p>
                See all your info if you are already signed in. Otherwise you
                will need to sign in first.
              </p>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
